### ISSUE TITLE
Load sortings

### ISSUE THREAD

**Issue by alexmorley** [flatironinstitute/neuropixels-data-sep-2020#14]
Load recordings mostly working for me now but can't get any of the sortings (using `nb.load_sorting`). Does this work for y'all locally at flatiron at the moment?

```
Traceback (most recent call last):                                                                                                                       
  File "scripts/download_sortings.py", line 22, in <module>                                                                                              
    sorting = nd.load_sorting(recording_id+':curated')                                                                                                   
  File "./neuropixels_data_sep_2020/recordings.py", line 47, in load_sorting                                                                             
    sorting = LabboxEphysSortingExtractor(uri)                                                                                                           
  File "./neuropixels_data_sep_2020/extractors/labboxephyssortingextractor.py", line 69, in __init__                                                     
    obj = _create_object_for_arg(arg, samplerate=samplerate)                                                                                             
  File "./neuropixels_data_sep_2020/extractors/labboxephyssortingextractor.py", line 51, in _create_object_for_arg                                       
    obj = kp.load_object(path)                                                                                                                           
  File "/home/alexmorley/anaconda3/envs/MYENV/lib/python3.8/site-packages/kachery_p2p/core.py", line 279, in load_object                                 
    local_path = load_file(uri, p2p=p2p, from_node=from_node, from_channel=from_channel)                                                                 
  File "/home/alexmorley/anaconda3/envs/MYENV/lib/python3.8/site-packages/kachery_p2p/core.py", line 130, in load_file                                   
    raise LoadFileError(f'Error loading file: {r["error"]}: {uri}')                                                                                      
kachery_p2p.exceptions.LoadFileError: Error loading file: File not found.: sha1://2fcfdec5894bbd9b9fb37b14fef9c47fcdd08ad2/cortexlab-single-phase-3-curat
ed.json 
```

**Comment by magland** [comment]
Thanks for the report (I need to remember that my laptop is not always turned on, haha).

Now it should be available, and I've made a script called scripts/download_all_sortings.py

It should only take a minute or so to download.

**Comment by alexmorley** [comment]
Yep yep all good 👍 thank you
