### ISSUE TITLE
Error while downloading paired recordings

### ISSUE THREAD

**Issue by yger** [flatironinstitute/neuropixels-data-sep-2020#26]
The script to download paired_english recordings is working, and several are downloaded, but then it crashes with the following message
 File "/usr/lib/
python3.8/http/client.py", line 551, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.8/http/client.py", line 518, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/http/client.py", line 583, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.8/http/client.py", line 553, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

There is no hurry, I guess some file is not complete on the server side?

**Comment by magland** [comment]
Our server ran out of disk space. I expect it to work now.
Also, there's a slow memory leak in the kachery-p2p daemon, and we need to restart the nodes periodically. That will be remedied once we release our new version of the protocol, which will be a much more stateless implementation.
